// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repositry

import (
	"database/sql"
	"time"
)

type Bookmark struct {
	UserID    string
	PostID    string
	CreatedAt time.Time
}

type Follow struct {
	FollowerID string
	FollowedID string
	CreatedAt  time.Time
}

type Notification struct {
	ID        string
	KindID    int32
	UserID    string
	SenderID  interface{}
	PostID    interface{}
	IsRead    bool
	CreatedAt time.Time
}

type NotificationKind struct {
	ID   int32
	Name string
}

type Post struct {
	ID               string
	UserID           string
	Title            string
	Content          string
	CreatedAt        time.Time
	ViewsCount       int32
	CommentsCount    int32
	FeaturedImageUrl sql.NullString
}

type PostComment struct {
	ID        string
	PostID    string
	UserID    string
	Content   string
	CreatedAt time.Time
}

type PostReaction struct {
	PostID    string
	UserID    string
	KindID    int32
	CreatedAt time.Time
}

type PostView struct {
	PostID    string
	UserID    string
	CreatedAt time.Time
}

type ReactionKind struct {
	ID   int32
	Name string
}

type RefreshToken struct {
	Token     string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID              string
	Name            string
	Username        string
	HashedPassword  string
	JoinedAt        time.Time
	PostsCount      int32
	FollowingCount  int32
	FollowersCount  int32
	ProfileImageUrl sql.NullString
}
