// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres_repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bookmark struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt time.Time
}

type Follow struct {
	FollowerID uuid.UUID
	FollowedID uuid.UUID
	CreatedAt  time.Time
}

type Notification struct {
	ID        uuid.UUID
	KindID    int32
	UserID    uuid.UUID
	SenderID  uuid.NullUUID
	PostID    uuid.NullUUID
	IsRead    bool
	CreatedAt time.Time
}

type NotificationKind struct {
	ID   int32
	Name string
}

type Post struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Title            string
	Content          string
	CreatedAt        time.Time
	ViewsCount       int32
	CommentsCount    int32
	FeaturedImageUrl sql.NullString
}

type PostComment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	UserID    uuid.UUID
	Content   string
	CreatedAt time.Time
}

type PostReaction struct {
	PostID    uuid.UUID
	UserID    uuid.UUID
	KindID    int32
	CreatedAt time.Time
}

type PostView struct {
	PostID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type ReactionKind struct {
	ID   int32
	Name string
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID              uuid.UUID
	Name            string
	Username        string
	HashedPassword  string
	JoinedAt        time.Time
	PostsCount      int32
	FollowingCount  int32
	FollowersCount  int32
	ProfileImageUrl sql.NullString
}
