// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification.sql

package postgres_repo

import (
	"context"
	"time"
)

const checkNotificationForUser = `-- name: CheckNotificationForUser :one
SELECT EXISTS(SELECT 1 FROM notifications WHERE id = $1 AND user_id = $2)
`

type CheckNotificationForUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) CheckNotificationForUser(ctx context.Context, arg CheckNotificationForUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkNotificationForUser, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications(id, kind_id, user_id, sender_id, post_id, is_read)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, kind_id, user_id, sender_id, post_id, is_read, created_at
`

type CreateNotificationParams struct {
	ID       string
	KindID   int32
	UserID   string
	SenderID interface{}
	PostID   interface{}
	IsRead   bool
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.KindID,
		arg.UserID,
		arg.SenderID,
		arg.PostID,
		arg.IsRead,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.KindID,
		&i.UserID,
		&i.SenderID,
		&i.PostID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getNotifications = `-- name: GetNotifications :many
SELECT 
    n.id,
    nk.name as kind,
    n.user_id,
    n.sender_id,
    n.post_id,
    n.is_read,
    n.created_at
FROM notifications n
JOIN notification_kinds nk ON nk.id = n.kind_id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT $2
OFFSET $3
`

type GetNotificationsParams struct {
	UserID string
	Limit  int32
	Offset int32
}

type GetNotificationsRow struct {
	ID        string
	Kind      string
	UserID    string
	SenderID  interface{}
	PostID    interface{}
	IsRead    bool
	CreatedAt time.Time
}

func (q *Queries) GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]GetNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsRow
	for rows.Next() {
		var i GetNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.UserID,
			&i.SenderID,
			&i.PostID,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsCount = `-- name: GetNotificationsCount :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
`

func (q *Queries) GetNotificationsCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNotificationsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnreadNotificationsCount = `-- name: GetUnreadNotificationsCount :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) GetUnreadNotificationsCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNotificationsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications SET is_read = true WHERE id = $1
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, id)
	return err
}
